#!/bin/bash
#
# install.sh
# bash <(curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/init)

# Die on failures
set -e

# Echo all commands
set -x

# Check for Homebrew, install if we don’t have it
if test ! $(which brew); then
    echo “Installing homebrew…”
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew -v
sudo chown -R $USER /usr/local/Cellar
brew update

curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/Brewfile_base --output ~/Brewfile_base
brew bundle -v --file=~/Brewfile_base

# VSCode
sudo xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app

code --install-extension be5invis.vscode-custom-css
code --install-extension Tyriar.sort-lines
code --install-extension webrender.synthwave-x-fluoromachine

curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/vscode/settings.json --output ~/Library/ApplicationSupport/Code/User/settings.json

# Zsh
curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/zsh/.zsh_antibody_plugins --output ~/.zsh_antibody_plugins
curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/zsh/.zshrc --output ~/.zshrc

source ~/.zshrc
