#!/bin/bash
#
# install.sh
# bash <(curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/init)

# Die on failures
set -e

# Echo all commands
set -x

# Check for Homebrew, install if we don’t have it
#if test ! $(which brew); then
#    echo “Installing homebrew…”
#    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#fi
type brew >/dev/null 2>&1 || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

export PATH="/opt/homebrew/bin:$PATH" >> ~/.zshrc
source ~/.zshrc

brew -v
# for 10.x
# sudo chown -R $USER /usr/local/Cellar

brew update

curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/Brewfile_base --output ~/Brewfile_base
brew bundle -v --file=~/Brewfile_base

# VSCode
sudo xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app
code --install-extension be5invis.vscode-custom-css
code --install-extension Tyriar.sort-lines
code --install-extension webrender.synthwave-x-fluoromachine
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension mikestead.dotenv
code --install-extension yzhang.markdown-all-in-one
code --install-extension chenzhe.split-line
code --install-extension jzarzoso.break-from-comma
code --install-extension ms-python.python


export SYNTHWAVE_PLUGIN_VER=$(code --list-extensions --show-versions | grep synthwave-x-fluoromachine | cut -d @ -f 2)
curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/vscode/settings.json --output ~/Library/Application\ Support/Code/User/settings.json

# Zsh
curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/zsh/.zsh_plugins.txt --output ~/.zsh_plugins.txt
curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/zsh/.zshrc --output ~/.zshrc
#TODO: make fluoromachine var for version
#cp ~/.vscode/extensions/webrender.synthwave-x-fluoromachine-${SYNTHWAVE_PLUGIN_VER}/synthwave-x-fluoromachine.itermcolors ~/Library/Application\ Support/iTerm2/DynamicProfiles/synthwave-x-fluoromachine.itermcolors
curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/iterm/synthwave-profile.json --output ~/Library/Application\ Support/iTerm2/DynamicProfiles/synthwave-profile.json

# setup python
curl -Ls https://raw.githubusercontent.com/kwoods/CONFIG.SYS/master/Brewfile_python --output ~/Brewfile_python
brew bundle -v --file=~/Brewfile_python
echo 'PATH=$(pyenv root)/shims:$PATH' >> ~/.zshrc
